### ISSUE TITLE
Doc and components includes

### ISSUE THREAD

**Issue by Soullivaneuh** [shaialon/ember-admin-dashboards#6]
Hi. Just found your work, just what I need, awesome!

I don't use ember-cli, just a symfony project with ember include.

I'm currently stucked with bootstrap combination and ember for collapsed box and sidebar.

Do you have some doc or could you please tell me how to include juste some parts of your projects to get it working?

Thanks.

**Comment by shaialon** [comment]
Hi @Soullivaneuh, 
Could you be more specific as to which parts you mean?
Do you user Ember without Ember-cli?

**Comment by Soullivaneuh** [comment]
Yes I'm using Ember without Ember-cli and your project seems to be closely linked with the cli.

My first question is how to use some part of your project with only emberJS.

Thanks.

**Comment by Soullivaneuh** [comment]
@shaialon Sorry but why closing this one without any answer / improvement?

**Comment by nisho** [comment]
@Soullivaneuh Well, I guess it's not really an issue if you just want to use the project without one of the project's prerequisites...
